<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/24 09:59:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=deploywebistrano',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
